apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  rootPassword: {{ .Values.mysql.rootPassword }}
  database: {{ .Values.mysql.database }}
  user: {{ .Values.mysql.user }}
  password: {{ .Values.mysql.password }}
