apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.database }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.user }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.mysql.password }}
        ports:
        - containerPort: 80
